name: Probar IPNS

on:
  workflow_dispatch:

jobs:
  resolver:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar IPFS
        run: |
          wget -q https://dist.ipfs.tech/kubo/v0.38.2/kubo_v0.38.2_linux-amd64.tar.gz
          tar -xzf kubo_v0.38.2_linux-amd64.tar.gz
          sudo bash kubo/install.sh

      - name: Inicializar IPFS
        run: |
          ipfs init --profile=server

      - name: Resolver segunda lista
        run: |
          ipfs name resolve \
            k51qzi5uqu5di462t7j4vu4akwfhvtjhy88qbupktvoacqfqe9uforjvhyi4wr
